/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smartdashboard.extensions;

import edu.wpi.first.smartdashboard.camera.WPICameraExtension;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Jon Buckley
 */
public class CameraOverlay extends WPICameraExtension
{

    protected int xCoord = 20, yCoord = 20;

    /**
     * Creates new form CameraOverlay
     */
    public CameraOverlay()
    {
        super();

        initComponents();

        repaint();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);

        if (xCoordField.getText().compareTo("") != 0)
        {
            xCoord = Integer.parseInt(xCoordField.getText());
        }
        if (yCoordField.getText().compareTo("") != 0)
        {
            yCoord = Integer.parseInt(yCoordField.getText());
        }

        g.setColor(Color.blue);
        g.fillRect(xCoord, yCoord, 2, 50);
        g.fillRect(xCoord, yCoord, 50, 2);
    }

    public void paintParent(Graphics g)
    {
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seperator = new javax.swing.JSeparator();
        xCoordLabel = new javax.swing.JLabel();
        yCoordLabel = new javax.swing.JLabel();
        yCoordField = new javax.swing.JFormattedTextField();
        xCoordField = new javax.swing.JFormattedTextField();

        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        xCoordLabel.setText("xCoord");

        yCoordLabel.setText("yCoord");

        yCoordField.setText("0");

        xCoordField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yCoordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yCoordField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xCoordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xCoordField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 304, Short.MAX_VALUE))
                    .addComponent(seperator))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCoordLabel)
                    .addComponent(xCoordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yCoordLabel)
                    .addComponent(yCoordField))
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator seperator;
    protected javax.swing.JFormattedTextField xCoordField;
    protected javax.swing.JLabel xCoordLabel;
    protected javax.swing.JFormattedTextField yCoordField;
    protected javax.swing.JLabel yCoordLabel;
    // End of variables declaration//GEN-END:variables
}
